name: Dev to Staging Pipeline

on:
  pull_request:
    branches:
      - staging
    types: [opened, synchronize, reopened]

jobs:
  # Backend Unit Tests (runs first to catch basic issues)
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd be-test
          npm ci

      - name: Run backend unit tests
        run: |
          cd be-test
          npm run test:unit

  # Integration Tests (runs after unit tests pass)
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd be-test
          npm ci

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to staging environment
        run: |
          cd be-test
          npm run cdk deploy -- --require-approval never

      - name: Run integration tests
        run: |
          cd be-test
          npm run test:integration

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: integration-test-results
          path: be-test/test-results/
          retention-days: 7
