name: Feature to Dev Pipeline

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]

jobs:
  # Backend Unit Tests
  backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd be-test
          npm ci

      - name: Run backend unit tests
        run: |
          cd be-test
          npm run test:unit

      - name: Run backend tests with coverage
        run: |
          cd be-test
          npm run test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./be-test/coverage/lcov.info
          flags: backend-unit-tests
          name: backend-coverage
          fail_ci_if_error: false

  # Code Quality Checks
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd be-test
          npm ci

      - name: Run backend linting
        run: |
          cd be-test
          npm run lint

      - name: Run backend type checking
        run: |
          cd be-test
          npm run type-check
