name: Feature to Staging Pipeline

on:
  pull_request:
    branches:
      - staging
    types: [opened, synchronize, reopened]

jobs:
  # Backend Unit Tests
  backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        run: |
          cd be-test
          npm ci

      - name: Run backend unit tests
        run: |
          cd be-test
          npm run test:unit

      - name: Run backend unit tests with coverage
        run: |
          cd be-test
          npm run test:unit:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./be-test/coverage/lcov.info
          flags: backend-unit-tests
          name: backend-coverage
          fail_ci_if_error: false
